replicaCount: 1
image:
  repository: myrepo/cnoe
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: cnoe-service
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
resources: {}
